branches:
  only:
    - main
language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed fego/udagram-api-feed
  - docker tag udagram-api-user fego/udagram-api-user
  - docker tag reverseproxy fego/reverseproxy
  - docker tag udagram-frontend fego/udagram-frontend

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fego/udagram-api-feed
  - docker push fego/udagram-api-user
  - docker push fego/reverseproxy
  - docker push fego/udagram-frontend