version: "3"
services:
  reverseproxy:
      image: reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: udagram-api-user
    environment:
      FWD_POSTGRES_USERNAME: $FWD_POSTGRES_USERNAME
      FWD_POSTGRES_PASSWORD: $FWD_POSTGRES_PASSWORD 
      FWD_POSTGRES_DB: $FWD_POSTGRES_DB 
      FWD_POSTGRES_HOST: $FWD_POSTGRES_HOST
      FWD_AWS_REGION: $FWD_AWS_REGION 
      FWD_AWS_PROFILE: $FWD_AWS_PROFILE 
      FWD_AWS_BUCKET: $FWD_AWS_BUCKET
      FWD_JWT_SECRET: $FWD_JWT_SECRET
      FWD_URL: $FWD_URL
  backend-feed:
    image: udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      FWD_POSTGRES_USERNAME: $FWD_POSTGRES_USERNAME
      FWD_POSTGRES_PASSWORD: $FWD_POSTGRES_PASSWORD 
      FWD_POSTGRES_DB: $FWD_POSTGRES_DB
      FWD_POSTGRES_HOST: $FWD_POSTGRES_HOST
      FWD_AWS_REGION: $FWD_AWS_REGION
      FWD_AWS_PROFILE: $FWD_AWS_PROFILE 
      FWD_AWS_BUCKET: $FWD_AWS_BUCKET
      FWD_JWT_SECRET: $FWD_JWT_SECRET
      FWD_URL: $FWD_URL
  frontend:
    image: udagram-frontend
    ports:
      - "8100:80"